#!/bin/bash -e

# Set Chromium as default browser

BROWSER_LOCATION=/usr/bin/chromium-browser
BROWSER_LAUNCHERS="x-www-browser gnome-www-browser"
BROWSER_SCHEMAS="http https about"

for browser_launcher in ${BROWSER_LAUNCHERS}; do
  echo "Setting default browser (${browser_launcher}) to be ${BROWSER_LOCATION}"
  set +e
    update-alternatives --remove ${browser_launcher} "${BROWSER_LOCATION}"
  set +e

  update-alternatives --install /usr/bin/${browser_launcher} ${browser_launcher} "${BROWSER_LOCATION}" 99
  update-alternatives --set ${browser_launcher} "${BROWSER_LOCATION}"
done

for browser_schema in ${BROWSER_SCHEMAS}; do
  gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults --type string \
    --set /desktop/gnome/url-handlers/${browser_schema}/command "${BROWSER_LOCATION} %s"
done

gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults --type string \
  --set /desktop/gnome/applications/browser/exec ${BROWSER_LOCATION}
