#!/usr/bin/python
# Check if we are under secure boot by reading the correspondent EFI var

EFIVARS = "/sys/firmware/efi/vars"
SECUREBOOT ="SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c"

f = open(EFIVARS + "/" + SECUREBOOT + "/data", "rb");
secure_boot = ord(f.read(1))
exit(secure_boot)
