#!/bin/bash

passed_apps=()
failed_apps=()

script=`basename $0`

USERID=`id -u`
if [ $USERID = 0 ]; then
    echo "Not allowed to run this program with superuser privileges"
    exit 1
fi

CORE_DESKTOPS=`grep -Rl X-Endless-Merged /usr/share/applications | sort`
CORE_APPS=
for desktop in $CORE_DESKTOPS
do
    app=`basename $desktop | sed 's/\(.*\)\..*/\1/'`
    CORE_APPS+="$app "
done

FLATPAK_APPS=`flatpak list --app | grep -v EknServices | cut -d'/' -f 1`

for app in $CORE_APPS $FLATPAK_APPS
do
    echo $app
    gtk-launch $app
    zenity --question --title=$script --text="Did $app launch successfully?" --ok-label="Yes" --cancel-label="No"
    if [ $? == "0" ]; then
	passed_apps+=($app)
    else
	failed_apps+=($app)
    fi
done

echo
echo "Passed apps:"
for app in "${passed_apps[@]}"
do
    echo $app
done
echo

echo "Failed apps:"
for app in "${failed_apps[@]}"
do
    echo $app
done
echo
