#!/bin/bash

echo "Killing com.endlessm.Clubhouse"
gdbus call --session \
    --dest com.endlessm.Clubhouse \
    --object-path /com/endlessm/Clubhouse \
    --method org.gtk.Actions.Activate quit [] []

echo "Resetting com.endlessm.GameStateService"
gdbus call --session \
    --dest com.endlessm.GameStateService \
    --object-path /com/endlessm/GameStateService \
    --method com.endlessm.GameStateService.Reset

echo "Removing com.endlessm.Fizzics state"
rm -f ~/.var/app/com.endlessm.Fizzics/data/webkitgtk/localstorage/*

echo "Resetting desktop icons"
eos-reset-desktop

echo "Done"
