#!/bin/bash -e

function usage {
    cat <<EOF
Usage:
    $0 STAGE [PASSWORD]
Arguments:
    STAGE     One of the following:
                - dev: development staging (requires password)
                - demo: beta testing in advance of production releases
                - prod: full production releases for general availability
    PASSWORD  Development password (for staging branch only)
EOF
}

if [ $# -lt 1 ] || [ $# -gt 2 ] ; then
    if [ $# -lt 1 ] ; then
        echo "Error: missing STAGE argument" >&2
    else
        echo "Error: extra arguments after STAGE PASSWORD" >&2
    fi
    echo >&2
    usage >&2
    exit 1
fi

STAGE="$1"

PASSWORD=
if [ $# -ge 2 ] ; then
    PASSWORD="$2"
fi

if [ $EUID != 0 ] ; then
    echo "Program requires superuser privileges" >&2
    exit 1
fi

if [ "$STAGE" == "dev" ] ; then
    if [ -z "$PASSWORD" ] ; then
	echo "Error: missing required PASSWORD for dev stage" >&2
	exit 1
    fi
    base_url="https://endless:${PASSWORD}@origin.ostree.endlessm.com/staging/dev"
elif [ "$STAGE" == "demo" ] ; then
    base_url="https://ostree.endlessm.com/staging/demo"
elif [ "$STAGE" == "prod" ] ; then
    base_url="https://ostree.endlessm.com/ostree"
else
    echo "Invalid STAGE -- must be dev, demo, or prod" >&2
    exit 1
fi

if [ -d /var/endless-extra/flatpak/repo ]; then
    flatpak_repo=/var/endless-extra/flatpak/repo
else
    flatpak_repo=/var/lib/flatpak/repo
fi

for remote in `flatpak remote-list --system | awk {'print $1'}` ; do
    url=$(ostree --repo="$flatpak_repo" config get 'remote "'"$remote"'".url')
    if [[ "$url" == *"ostree.endlessm.com"* ]] ; then
        repo=${url##*/}
        new_url="${base_url}/${repo}"
        if [ "$remote" == "eos-sdk" ] && [ "$STAGE" == "dev" ] ; then
            # eos-sdk's dev is passwordless
            new_url="https://ostree.endlessm.com/staging/dev/${repo}"
        fi
        echo "Setting flatpak $remote URL to $new_url"
        flatpak remote-modify "$remote" --url="$new_url"

        # Delete the appstream data and fetch it for the new remote;
        # otherwise an update might be rejected as a downgrade
        # https://github.com/flatpak/flatpak/issues/1615#issuecomment-385133763
        rm -rf "$(dirname $flatpak_repo)/appstream/$remote"
        for arch in `flatpak --supported-arches`; do
            ostree --repo="$flatpak_repo" refs --delete "$remote:appstream/$arch"
            # This might fail for the secondary architecture
            flatpak update --appstream --arch="$arch" "$remote" >/dev/null 2>&1 || true
        done

        # Do the same with ostree-metadata
        # https://github.com/flatpak/flatpak/issues/1477#issuecomment-372167938
        ostree --repo="$flatpak_repo" refs --delete "$remote:ostree-metadata"
        # Try to update ostree-metadata, but don't bail on failure
        flatpak remote-ls "$remote" >/dev/null || true
    fi
done
