#!/bin/bash -e

# Resets a user's password
# Except for the special shared account,
# the user will be asked for a password on next login

if [ "$#" -ne 2 ]; then
    echo "usage: $0 device username"
    echo "(run eos-list-users to see a list of devices and usernames)"
    exit
fi
DEVICE=$1
USERNAME=$2

USERID=$(id -u)
if [ "$USERID" != "0" ]; then
    echo "Program requires superuser privileges"
    exit 1
fi

if [ $USERNAME = root ]; then
    echo "Resetting root password not allowed"
    exit
elif [ $USERNAME = shared ]; then
    # For the shared account, set the change date (days since Jan 1, 1970)
    # to today (so that user will not be asked to set a password)
    DATE=$((`date +"%s"` / 86400))
else
    # Any other user should set the password on next login
    DATE=0
fi

MOUNT=`mktemp -d`

cleanup() {
    set +e
    umount $MOUNT
    rmdir $MOUNT
}
trap cleanup EXIT

mount $DEVICE $MOUNT
CURRENT=$(ostree admin --sysroot=$MOUNT --print-current-dir)
sed -i "s/$USERNAME:[^:]*:[^:]*:/$USERNAME::$DATE:/" $CURRENT/etc/shadow
