#!/bin/bash -e

# OSTree dev repo URL settings.
OSTREE_USER=endless
OSTREE_HOST=origin.ostree.endlessm.com
OSTREE_DEV_ROOT=staging/dev

function usage {
    cat <<EOF
Usage:
    $0 STAGE [PASSWORD]
Arguments:
    STAGE     One of the following:
                - dev: development staging (requires password)
                - demo: beta testing in advance of production releases
                - prod: full production releases for general availability
    PASSWORD  Development password (for staging branch only)
EOF
}

if [ $# -lt 1 ] || [ $# -gt 2 ] ; then
    if [ $# -lt 1 ] ; then
        echo "Error: missing STAGE argument" >&2
    else
        echo "Error: extra arguments after STAGE PASSWORD" >&2
    fi
    echo >&2
    usage >&2
    exit 1
fi

STAGE="$1"

PASSWORD=
if [ $# -ge 2 ] ; then
    PASSWORD="$2"
fi

if [ $EUID != 0 ] ; then
    echo "Program requires superuser privileges" >&2
    exit 1
fi

if [ "$STAGE" == "dev" ] ; then
    if [ -z "$PASSWORD" ] ; then
	echo "Error: missing required PASSWORD for dev stage" >&2
	exit 1
    fi
elif [ "$STAGE" == "demo" ] ; then
    echo "Currently this script only supports the dev stage" >&2
    exit 1
elif [ "$STAGE" == "prod" ] ; then
    echo "Currently this script only supports the dev stage" >&2
    exit 1
else
    echo "Invalid STAGE -- must be dev, demo, or prod" >&2
    exit 1
fi

if [ -d /var/endless-extra/flatpak/repo ]; then
    flatpak_repo=/var/endless-extra/flatpak/repo
else
    flatpak_repo=/var/lib/flatpak/repo
fi

runtime_url=$(ostree --repo="$flatpak_repo" config get 'remote "eos-runtimes".url')
runtime_repo=${runtime_url##*/}
new_runtime_url="https://${OSTREE_USER}:${PASSWORD}@${OSTREE_HOST}/${OSTREE_DEV_ROOT}/${runtime_repo}"

echo "Setting flatpak runtimes URL to $new_runtime_url"
flatpak remote-modify eos-runtimes --url="$new_runtime_url"

apps_url=$(ostree --repo="$flatpak_repo" config get 'remote "eos-apps".url')
apps_repo=${apps_url##*/}
new_apps_url="https://${OSTREE_USER}:${PASSWORD}@${OSTREE_HOST}/${OSTREE_DEV_ROOT}/${apps_repo}"

echo "Setting flatpak apps URL to $new_apps_url"
flatpak remote-modify eos-apps --url="$new_apps_url"
