#!/bin/bash -e

# Adds an application to the desktop
# The appname.desktop file must already exist (typically in
# /var/lib/flatpak/exports/share/applications/ or
# /usr/share/applications or ~/.local/share/applications)

if [ $# -lt 1 ] || [ $1 == "-h" ] || [ $1 == "--help" ]; then
    echo "Usage:"
    echo "   $(basename $0) appid"
    echo ""
    echo "Where:"
    echo "   appid = application id (where desktop file is named appid.desktop)"
    exit
fi

APPID="$1"

dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.AppStore.AddApplication string:$APPID.desktop
