#!/bin/bash -e

# Detect the plugged in USB storage and prompt users
# that the contents of the storage will be erased
# and the whole disk will be reformatted to a single
# FAT32 partition (dos).
# Then copy both eos-metrics-collector and the
# eos-metrics-uploader with .exe extension for the
# users to execute to collect/upload offline metrics
# data.

USB_DISK_NUM=0
EOSMETRICS_LIBEXEC="/usr/share/libexec/eos-metrics"

USERID=$(id -u)
if [ "$USERID" != "0" ]; then
    echo "Program requires superuser privileges" >&2
    exit 1
fi

prompt_input()
{
    echo "
         "
    read -p "Please enter the disk number you want to create for metrics: "
    response="${REPLY,,}" # to lower
    if [[ ! "$response" =~ ^[1-9]$ ]]; then
        echo " Please re-input your selection "
        prompt_input
    fi
    if [ $((response)) -gt $((USB_DISK_NUM)) ]; then
        echo " Please re-input your selection "
        prompt_input
    fi

    USER_CHOICE=$response
}

for device in /sys/block/*
do
    if udevadm info --query=property --path=$device | grep -q ^ID_BUS=usb
    then
        DISK[$USB_DISK_NUM]="/dev/${device##*/}"
        ((USB_DISK_NUM=USB_DISK_NUM+1))
        echo "$USB_DISK_NUM) / ${DISK[$((USB_DISK_NUM-1))]}"
        echo "`lsblk -o name,label /dev/${device##*/}`"
    fi
done

if [ $USB_DISK_NUM -eq 0 ]; then
    echo "Please plug in the USB storage device."
    exit 1
fi

prompt_input
TARGET_DISK=${DISK[$((USER_CHOICE-1))]}
echo "disk name $TARGET_DISK"

OLD_PARTS="$(lsblk --noheadings --output PATH $TARGET_DISK | sed '1d')"
if [ ! -z "$OLD_PARTS" ]; then
    for part in $OLD_PARTS; do
        if findmnt --noheadings --output TARGET --source $part ; then
            udisksctl unmount -b "$part" --no-user-interaction --force
        fi
    done
fi

echo "== Writing a new partition table to disk =="
TABLE="label: dos
start=2048, type=c"
echo "$TABLE" | sfdisk --quiet --force --wipe always "$TARGET_DISK"
udevadm settle
partprobe "$TARGET_DISK"

PART="$(lsblk --noheadings --output PATH $TARGET_DISK | sed '1d')"
echo "== Formatting the new partition $PART =="
mkfs.vfat -n EOSMETRICS "$PART"
udevadm settle

echo "== Mounting $PART =="
if ! udisksctl mount -b "$PART" --no-user-interaction; then
    echo "Failed to mount FAT32 on $PART- exiting"
    exit 1
fi

echo "== Populating the partition =="
TARGET_MOUNTPOINT="$(findmnt --noheadings --output TARGET --source $PART)"
cp -v $EOSMETRICS_LIBEXEC/metrics.py "$TARGET_MOUNTPOINT"
cp -v $EOSMETRICS_LIBEXEC/eos-metrics-collector.exe "$TARGET_MOUNTPOINT"
cp -v $EOSMETRICS_LIBEXEC/eos-metrics-uploader.exe "$TARGET_MOUNTPOINT"

echo "== Unmounting $PART =="
udisksctl unmount -b "$PART" --no-user-interaction
sync
echo "The USB device can now be removed and used to collect offline metrics"
