#!/bin/bash

# Lists all users (i.e., all home directories on /dev/sda2)

DEVICE=/dev/sda2
MOUNT=/mnt/sda2

USERID=$(id -u)
if [ "$USERID" != "0" ]; then
    echo "Program requires superuser privileges"
    exit 1
fi

mkdir -p $MOUNT
mount $DEVICE $MOUNT
ls $MOUNT/home

umount $MOUNT
rmdir $MOUNT
