#!/bin/bash -e

STAGING_SERVER="http://staging.appupdates.endlessm.com"

function usage {
    cat <<EOF
Invalid option: $1

Valid options:
    -m, --metrics     Configure Metrics System for Dev.
    -a, --apps        Configure App Server for Staging.
    -o, --ostree      Configure OSTree for Staging.
EOF
}

METRICS=true
APPS=true
OSTREE=true
if [ $# -gt 0 ]; then
    METRICS=false
    APPS=false
    OSTREE=false
    while [ $# -gt 0 ]; do
        case "$1" in
            -m|--metrics)
                METRICS=true
                shift
                ;;
            -a|--apps)
                APPS=true
                shift
                ;;
            -o|--ostree)
                OSTREE=true
                shift
                ;;
            *)
                usage $1
                exit 1
                ;;
        esac
    done
fi

# Check that script was run with superuser priviliges.
if [[ $EUID != 0 ]]; then
    echo "$0 requires superuser privileges."
    exit 1
fi

# Check if master image.
if ostree admin status | grep -q "master"; then
    read -p "Detected master image. Are you sure you wish to continue? [Y/n] " response
    case $response in
        [yY]* | '') ;;
        *) exit 1 ;;
    esac
fi

# Set metrics env to dev.
if $METRICS; then
    echo "Configuring Metrics System for Dev."
    eos-select-metrics-env dev
fi

# Change app server to staging.
if $APPS; then
    echo "Configuring App Server for Staging."
    eos-select-app-server $STAGING_SERVER
fi

# Change OSTree server and check it.
if $OSTREE; then
    # Get the current refspec.
    refspec=$(ostree admin status | awk '/refspec:/{print $3}' | head -n1)
    branch=${refspec#*:}
    arch=${branch#*/}

    # Get the OS major.minor version,
    version=$(. /etc/os-release && echo $VERSION | cut -d. -f1-2)

    # Construct the new branch.
    new_branch="eos${version}/${arch}"

    # Get the current URL and convert to staging.
    url=$(ostree config get 'remote "eos".url')
    new_url=$(echo $url | sed 's,/ostree/,/staging/dev/,')

    echo "Configuring OSTree for Staging."
    # HACK! HACK! HACK! ostree admin set-origin is horribly broken as of
    # ostree 2015.7. We have to delete the remote(!) first, and then move
    # the remote config into the main config file.
    # Upstream bug at https://bugzilla.gnome.org/show_bug.cgi?id=753373
    ostree remote delete eos
    ostree admin set-origin eos "$new_url" "$new_branch" \
        --set=branches="${new_branch};"
    printf "\n" >> /ostree/repo/config
    cat /etc/ostree/remotes.d/eos.conf >> /ostree/repo/config
    rm /etc/ostree/remotes.d/eos.conf

    echo "Killing eos-updater."
    killall eos-updater &>/dev/null
    echo "All done!"
fi
