#!/bin/bash

passed_apps=()
failed_apps=()

script=`basename $0`

CORE_APPS=`grep -Rl X-Endless-Merged /usr/share/applications | sort`
BUNDLE_APPS=/endless/share/applications/*.desktop

USERID=`id -u`
if [ $USERID = 0 ]; then
    echo "Not allowed to run this program with superuser privileges"
    exit 1
fi

for desktop in $CORE_APPS $BUNDLE_APPS
do
    echo $desktop
    app=`basename $desktop | sed 's/\(.*\)\..*/\1/'`
    gtk-launch $app
    zenity --question --title=$script --text="Did $app launch successfully?" --ok-label="Yes" --cancel-label="No"
    if [ $? == "0" ]; then
	passed_apps+=($app)
    else
	failed_apps+=($app)
    fi
done

echo
echo "Passed apps:"
for app in "${passed_apps[@]}"
do
    echo $app
done
echo

echo "Failed apps:"
for app in "${failed_apps[@]}"
do
    echo $app
done
echo
