#!/bin/bash -e

# Resets a user's password
# Except for the special shared account,
# the user will be asked for a password on next login

BOOTDEV=/dev/sda1
DEVICE=/dev/sda2
MOUNT=/mnt/sda2

if [ -z "$1" ]; then
    echo usage: $0 username
    exit
fi
USERNAME=$1

USERID=$(id -u)
if [ "$USERID" != "0" ]; then
    echo "Program requires superuser privileges"
    exit 1
fi

if [ $USERNAME = root ]; then
    echo "Resetting root password not allowed"
    exit
elif [ $USERNAME = shared ]; then
    # For the shared account, set the change date (days since Jan 1, 1970)
    # to today (so that user will not be asked to set a password)
    DATE=$((`date +"%s"` / 86400))
else
    # Any other user should set the password on next login
    DATE=0
fi

cleanup() {
    set +e
    umount $MOUNT/boot
    umount $MOUNT
    rmdir $MOUNT
}
trap cleanup EXIT

mkdir -p $MOUNT
mount $DEVICE $MOUNT
mount $BOOTDEV $MOUNT/boot
CURRENT=$(ostree admin --sysroot=$MOUNT --print-current-dir)
sed -i "s/$USERNAME:[^:]*:[^:]*:/$USERNAME::$DATE:/" $CURRENT/etc/shadow
